### ISSUE TITLE
Errors with parsing with multiple threads under load

### ISSUE THREAD

**Issue by cheziyi** [bazzilic/PrismaDB-QueryParser-MySQL#11]
Works fine with just 1 thread.
```
21/4/2018 3:57:34 AM | Received Query | Thread: 4
SELECT a, b, c, d, e, f FROM bafmcbxr;

21/4/2018 3:57:34 AM | Error Message | Thread: 4
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Irony.Parsing.Construction.ParserStateData.AddItem(LR0Item core)
   at Irony.Parsing.Construction.ParserStateData.AddItem(LR0Item core)
   at Irony.Parsing.Construction.ParserStateData..ctor(ParserState state, LR0ItemSet kernelCores)
   at Irony.Parsing.Construction.ParserDataBuilder.FindOrCreateState(LR0ItemSet coreItems)
   at Irony.Parsing.Construction.ParserDataBuilder.ExpandParserStateList(Int32 initialIndex)
   at Irony.Parsing.Construction.ParserDataBuilder.CreateParserStates()
   at Irony.Parsing.Construction.ParserDataBuilder.Build()
   at Irony.Parsing.Construction.LanguageDataBuilder.Build()
   at Irony.Parsing.LanguageData..ctor(Grammar grammar)
   at PrismaDB.QueryParser.SqlParser.Parse(String source)
   at PrismaDB.QueryParser.SqlParser.ParseToAST(String source)
   at PrismaDB.Proxy.MySQL.QueryExecutor.Execute(String batchMessage) in C:\Users\calvin\Documents\Repos\PrismaDB\PrismaDB-Proxy-MySQL\PrismaDB-Proxy-MySQL\QueryExecutor.cs:line 25
   at PrismaDB.Proxy.MySQL.SocketServer.HandleClient(Object obj) in C:\Users\calvin\Documents\Repos\PrismaDB\PrismaDB-Proxy-MySQL\PrismaDB-Proxy-MySQL\SocketServer.cs:line 75
```

```
21/4/2018 3:58:42 AM | Received Query | Thread: 6
CREATE TABLE jarrgvnq(a INT,  b INT,  c INT, d VARCHAR(20), e VARCHAR(20), f VARCHAR(20));

21/4/2018 3:58:42 AM | Error Message | Thread: 6
Object reference not set to an instance of an object.
   at Irony.Parsing.Construction.ParserStateData.GetNextState(BnfTerm shiftTerm)
   at Irony.Parsing.PrecedenceHint.Apply(LanguageData language, LRItem owner)
   at Irony.Parsing.Construction.ParserDataBuilder.ApplyHints()
   at Irony.Parsing.Construction.ParserDataBuilder.Build()
   at Irony.Parsing.Construction.LanguageDataBuilder.Build()
   at Irony.Parsing.LanguageData..ctor(Grammar grammar)
   at PrismaDB.QueryParser.SqlParser.Parse(String source)
   at PrismaDB.QueryParser.SqlParser.ParseToAST(String source)
   at PrismaDB.Proxy.MySQL.QueryExecutor.Execute(String batchMessage) in C:\Users\calvin\Documents\Repos\PrismaDB\PrismaDB-Proxy-MySQL\PrismaDB-Proxy-MySQL\QueryExecutor.cs:line 25
   at PrismaDB.Proxy.MySQL.SocketServer.HandleClient(Object obj) in C:\Users\calvin\Documents\Repos\PrismaDB\PrismaDB-Proxy-MySQL\PrismaDB-Proxy-MySQL\SocketServer.cs:line 75
```

**Comment by cheziyi** [comment]
Issue should be in proxy repo.
